name: release-checksums

on:
  release:
    types: [published, edited]
  workflow_dispatch:
    inputs:
      tag:
        description: "Release tag to verify (e.g., HR-StepA-PartB-beta0.08-Delta1100)"
        required: true

jobs:
  build-sums:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    outputs:
      should_verify: ${{ steps.mark.outputs.should_verify }}
    steps:
      - id: settag
        name: Compute tag
        run: |
          if [ -n "${{ github.event.release.tag_name }}" ]; then
            echo "tag=${{ github.event.release.tag_name }}" >> "$GITHUB_OUTPUT"
          else
            echo "tag=${{ github.event.inputs.tag }}" >> "$GITHUB_OUTPUT"
          fi

      - id: detect
        name: Detect release assets
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -e
          TAG="${{ steps.settag.outputs.tag }}"
          CNT=$(gh release view "$TAG" --repo "${{ github.repository }}" --json assets --jq '.assets | length')
          echo "count=$CNT" >> "$GITHUB_OUTPUT"
          echo "Assets count: $CNT"

      - name: Checkout (tag) con LFS
        uses: actions/checkout@v4
        with:
          ref: ${{ steps.settag.outputs.tag }}
          lfs: true

      - name: Instalar jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Generar SHA256SUMS.txt
        if: ${{ steps.detect.outputs.count != '0' }}
        working-directory: HR-StepA
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -e
          # Descarga todos los assets del release al directorio actual (HR-StepA)
          gh release download "${{ steps.settag.outputs.tag }}" --repo "${{ github.repository }}" -D .
          ls -la . || true

          # Manifest en raíz
          test -f BEST_manifest.json || { echo "No existe BEST_manifest.json"; exit 1; }

          # Rutas desde el manifest (pueden venir con prefijo out/)
          ASSETS_FROM_MANIFEST=$(jq -r '.assets.best_zip, .assets.inputs_zip, .assets.lemma_pdf' BEST_manifest.json)

          # Extras en raíz
          EXTRAS="BEST_summary.txt"
          CSV_GLOB="summary_sweep_beta*.csv"

          # Salida en raíz
          : > SHA256SUMS.txt

          # Hashear assets del manifest (pelando 'out/' si aparece)
          for f in ${ASSETS_FROM_MANIFEST} ${EXTRAS}; do
            f2=${f#out/}
            if [ -f "$f2" ]; then
              sha256sum "$f2" >> SHA256SUMS.txt
            else
              echo "WARN: falta $f2" >&2
            fi
          done

          # Hashear CSV opcionales
          for f in $CSV_GLOB; do
            [ -f "$f" ] && sha256sum "$f" >> SHA256SUMS.txt || true
          done

          cat SHA256SUMS.txt

      - id: mark
        if: ${{ steps.detect.outputs.count != '0' }}
        run: echo "should_verify=true" >> "$GITHUB_OUTPUT"

      - name: Subir SHA256SUMS.txt al release
        if: ${{ steps.detect.outputs.count != '0' }}
        uses: softprops/action-gh-release@v2
        with:
          files: HR-StepA/SHA256SUMS.txt
          tag_name: ${{ steps.settag.outputs.tag }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  verify-on-windows:
    runs-on: windows-latest
    needs: build-sums
    if: ${{ needs.build-sums.outputs.should_verify == 'true' }}
    steps:
      - id: settag
        name: Compute tag
        shell: pwsh
        run: |
          if ("${{ github.event.release.tag_name }}") {
            "tag=${{ github.event.release.tag_name }}" | Out-File -FilePath $env:GITHUB_OUTPUT -Encoding utf8 -Append
          } else {
            "tag=${{ github.event.inputs.tag }}" | Out-File -FilePath $env:GITHUB_OUTPUT -Encoding utf8 -Append
          }

      - name: Checkout (tag) con LFS
        uses: actions/checkout@v4
        with:
          ref: ${{ steps.settag.outputs.tag }}
          lfs: true

      - name: Descargar SHA256SUMS.txt del release
        working-directory: HR-StepA
        shell: pwsh
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          $tag = "${{ steps.settag.outputs.tag }}"
          gh release download $tag --repo "${{ github.repository }}" --skip-existing -p SHA256SUMS.txt -D .
          Get-ChildItem .

      - name: Verificar checksums (PowerShell)
        working-directory: HR-StepA
        shell: pwsh
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          $tag = "${{ steps.settag.outputs.tag }}"
          # Asegura que los archivos a verificar estén presentes en HR-StepA\
          gh release download $tag --repo "${{ github.repository }}" --skip-existing -D .
          $sumsPath = Join-Path (Get-Location) 'SHA256SUMS.txt'
          if (!(Test-Path $sumsPath)) { Write-Error "No se encontró $sumsPath"; exit 1 }

          $lines  = Get-Content $sumsPath | Where-Object { $_ -match '\S' }
          $errors = 0
          foreach ($line in $lines) {
            # Formato: "<hash><2+ espacios><archivo>"
            $parts = $line -split '\s{2,}', 2
            if ($parts.Count -lt 2) { Write-Host "Saltando línea: $line"; continue }
            $expected = $parts[0].ToLower()
            $file     = $parts[1]

            if (!(Test-Path $file)) { Write-Host "MISSING  $file"; $errors++; continue }
            $got = (Get-FileHash -Algorithm SHA256 $file).Hash.ToLower()
            if ($got -ne $expected) { Write-Host "MISMATCH $file"; $errors++ } else { Write-Host "OK $file" }
          }
          if ($errors -gt 0) { Write-Error "Hubo $errors errores de checksum"; exit 1 }; exit 0

