name: release-checksums

on:
  release:
    types: [published, edited]
  workflow_dispatch:
    inputs:
      tag:
        description: "Release tag to verify (e.g., HR-StepA-PartB-beta0.08-Delta1100)"
        required: true

jobs:
  build-sums:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - id: settag
        name: Compute tag
        run: |
          if [ -n "${{ github.event.release.tag_name }}" ]; then
            echo "tag=${{ github.event.release.tag_name }}" >> "$GITHUB_OUTPUT"
          else
            echo "tag=${{ inputs.tag }}" >> "$GITHUB_OUTPUT"
          fi

      - name: Checkout (tag) con LFS
        uses: actions/checkout@v4
        with:
          ref: ${{ steps.settag.outputs.tag }}
          lfs: true

      - name: Instalar jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Verificar y generar checksums si hay assets
        working-directory: HR-StepA
        run: |
          set -e
          # Intentar descargar assets, continuar si no hay
          if gh release download "${{ steps.settag.outputs.tag }}" --repo "${{ github.repository }}" -D . 2>/dev/null; then
            echo "Assets downloaded, generating checksums..."
            test -f out/BEST_manifest.json || { echo "No existe out/BEST_manifest.json"; exit 1; }
            ASSETS_FROM_MANIFEST=$(jq -r '.assets.best_zip, .assets.inputs_zip, .assets.lemma_pdf' out/BEST_manifest.json)
            EXTRAS="out/BEST_summary.txt"
            CSV_GLOB="out/summary_sweep_beta*.csv"
            : > out/SHA256SUMS.txt
            for f in ${ASSETS_FROM_MANIFEST} ${EXTRAS}; do
              if [ -f "$f" ]; then
                sha256sum "$f" >> out/SHA256SUMS.txt
              else
                echo "WARN: falta $f" >&2
              fi
            done
            for f in $CSV_GLOB; do
              [ -f "$f" ] && sha256sum "$f" >> out/SHA256SUMS.txt || true
            done
            cat out/SHA256SUMS.txt
          else
            echo "No assets found in this release, skipping checksum generation"
            exit 0
          fi
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Subir SHA256SUMS.txt al release
        if: success()
        uses: softprops/action-gh-release@v2
        with:
          files: HR-StepA/out/SHA256SUMS.txt
          tag_name: ${{ steps.settag.outputs.tag }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  verify-on-windows:
    runs-on: windows-latest
    needs: build-sums
    if: success()
    steps:
      - id: settag
        name: Compute tag
        shell: bash
        run: |
          if [ -n "${{ github.event.release.tag_name }}" ]; then
            echo "tag=${{ github.event.release.tag_name }}" >> "$GITHUB_OUTPUT"
          else
            echo "tag=${{ inputs.tag }}" >> "$GITHUB_OUTPUT"
          fi

      - name: Checkout (tag) con LFS
        uses: actions/checkout@v4
        with:
          ref: ${{ steps.settag.outputs.tag }}
          lfs: true

      - name: Descargar SHA256SUMS.txt del release
        working-directory: HR-StepA
        shell: pwsh
        run: |
          $tag = "${{ steps.settag.outputs.tag }}"
          gh release download $tag -p SHA256SUMS.txt -D out --repo "${{ github.repository }}"
          Get-ChildItem out
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Verificar checksums con tu script
        working-directory: HR-StepA
        shell: pwsh
        run: .\verify_release.ps1 -SumsPath .\out\SHA256SUMS.txt
