name: release-checksums

on:
  release:
    types: [published, edited]
  workflow_dispatch:
    inputs:
      tag:
        description: "Release tag to verify (e.g., HR-StepA-PartB-beta0.08-Delta1100)"
        required: true

jobs:
  build-sums:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    outputs:
      should_verify: ${{ steps.mark.outputs.should_verify }}
    steps:
      - id: settag
        name: Compute tag
        run: |
          if [ -n "${{ github.event.release.tag_name }}" ]; then
            echo "tag=${{ github.event.release.tag_name }}" >> "$GITHUB_OUTPUT"
          else
            echo "tag=${{ github.event.inputs.tag }}" >> "$GITHUB_OUTPUT"
          fi

      - id: detect
        name: Detect release assets
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -e
          TAG="${{ steps.settag.outputs.tag }}"
          CNT=$(gh release view "$TAG" --repo "${{ github.repository }}" --json assets --jq '.assets | length')
          echo "count=$CNT" >> "$GITHUB_OUTPUT"
          echo "Assets count: $CNT"

      - name: Checkout (tag) con LFS
        uses: actions/checkout@v4
        with:
          ref: ${{ steps.settag.outputs.tag }}
          lfs: true

      - name: Instalar jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Generar SHA256SUMS.txt
        if: ${{ steps.detect.outputs.count != '0' }}
        working-directory: HR-StepA
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -e
          gh release download "${{ steps.settag.outputs.tag }}" --repo "${{ github.repository }}" -D .
          test -f BEST_manifest.json || { echo "No existe BEST_manifest.json"; exit 1; }
          ASSETS_FROM_MANIFEST=$(jq -r '.assets.best_zip, .assets.inputs_zip, .assets.lemma_pdf' BEST_manifest.json)
          EXTRAS="BEST_summary.txt"
          CSV_GLOB="summary_sweep_beta*.csv"
          : > SHA256SUMS.txt
          for f in ${ASSETS_FROM_MANIFEST} ${EXTRAS}; do
            if [ -f "$f" ]; then
              sha256sum "$f" >> SHA256SUMS.txt
            else
              echo "WARN: falta $f" >&2
            fi
          done
          for f in $CSV_GLOB; do
            [ -f "$f" ] && sha256sum "$f" >> SHA256SUMS.txt || true
          done
          cat out/SHA256SUMS.txt

      - id: mark
        if: ${{ steps.detect.outputs.count != '0' }}
        run: echo "should_verify=true" >> "$GITHUB_OUTPUT"

      - name: Subir SHA256SUMS.txt al release
        if: ${{ steps.detect.outputs.count != '0' }}
        uses: softprops/action-gh-release@v2
        with:
          files: HR-StepA/SHA256SUMS.txt
          tag_name: ${{ steps.settag.outputs.tag }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  verify-on-windows:
    runs-on: windows-latest
    needs: build-sums
    if: ${{ needs.build-sums.outputs.should_verify == 'true' }}
    steps:
      - id: settag
        name: Compute tag
        shell: pwsh
        run: |
          if ("${{ github.event.release.tag_name }}") {
            "tag=${{ github.event.release.tag_name }}" | Out-File -FilePath $env:GITHUB_OUTPUT -Encoding utf8 -Append
          } else {
            "tag=${{ github.event.inputs.tag }}" | Out-File -FilePath $env:GITHUB_OUTPUT -Encoding utf8 -Append
          }

      - name: Checkout (tag) con LFS
        uses: actions/checkout@v4
        with:
          ref: ${{ steps.settag.outputs.tag }}
          lfs: true

      - name: Descargar SHA256SUMS.txt del release
        working-directory: HR-StepA
        shell: pwsh
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          $tag = "${{ steps.settag.outputs.tag }}"
          New-Item -ItemType Directory -Force out | Out-Null
          gh release download $tag --repo "${{ github.repository }}" -p SHA256SUMS.txt -D out
          Get-ChildItem out

      - name: Verificar checksums con tu script
        working-directory: HR-StepA
        shell: pwsh
        run: .\verify_release.ps1 -SumsPath .\out\SHA256SUMS.txt



