name: release-checksums

on:
  release:
    types: [published, edited]
  workflow_dispatch:
    inputs:
      tag:
        description: "Release tag to verify (e.g., HR-StepA-PartB-beta0.08-Delta1100)"
        required: true

jobs:
  build-sums:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - id: settag
        name: Compute tag
        run: |
          if [ -n "${{ github.event.release.tag_name }}" ]; then
            echo "tag=${{ github.event.release.tag_name }}" >> "$GITHUB_OUTPUT"
          else
            echo "tag=${{ github.event.inputs.tag }}" >> "$GITHUB_OUTPUT"
          fi

      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Download release assets
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          mkdir -p release_assets
          gh release download "${{ steps.settag.outputs.tag }}" -D release_assets
          ls -la release_assets

      - name: Generate SHA256SUMS.txt from downloaded assets
        run: |
          set -e
          cd release_assets
          : > ../SHA256SUMS.txt
          for f in *; do
            [ "$f" = "SHA256SUMS.txt" ] && continue
            [ -f "$f" ] && sha256sum "$f" >> ../SHA256SUMS.txt
          done
          cd ..
          echo "=== SHA256SUMS.txt ==="
          cat SHA256SUMS.txt

      - name: Upload SHA256SUMS.txt to release
        uses: softprops/action-gh-release@v2
        with:
          files: SHA256SUMS.txt
          tag_name: ${{ steps.settag.outputs.tag }}
          overwrite: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  verify-on-windows:
    runs-on: windows-latest
    needs: build-sums
    steps:
      - id: settag
        name: Compute tag (pwsh)
        shell: pwsh
        run: |
          if ("${{ github.event.release.tag_name }}") {
            "tag=${{ github.event.release.tag_name }}" | Out-File -FilePath $env:GITHUB_OUTPUT -Encoding utf8 -Append
          } else {
            "tag=${{ github.event.inputs.tag }}" | Out-File -FilePath $env:GITHUB_OUTPUT -Encoding utf8 -Append
          }

      - name: Download all release assets (incl. SHA256SUMS.txt)
        shell: pwsh
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          $tag = "${{ steps.settag.outputs.tag }}"
          New-Item -ItemType Directory -Force out | Out-Null
          gh release download $tag -D out
          Get-ChildItem out

      - name: Verify checksums (PowerShell)
        shell: pwsh
        run: |
          $sums = Join-Path out "SHA256SUMS.txt"
          if (-not (Test-Path $sums)) { throw "No se encontró SHA256SUMS.txt en out/" }
          $lines = Get-Content $sums
          $errors = 0
          foreach ($line in $lines) {
            if ($line -match '^\s*([0-9A-Fa-f]{64})\s+(.+)$') {
              $expected = $matches[1].ToLower()
              $fname = $matches[2]
              $path = Join-Path out $fname
              if (Test-Path $path) {
                $actual = (Get-FileHash -Algorithm SHA256 $path).Hash.ToLower()
                if ($actual -ne $expected) { Write-Error "HASH MISMATCH: $fname"; $errors++ }
              } else {
                Write-Error "MISSING FILE: $fname"
                $errors++
              }
            }
          }
          if ($errors -gt 0) { throw "Fallo verificación: $errors error(es)" }
