name: run-checksums (wrapper)

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Release tag (e.g., HR-StepA-PartB-beta0.08-Delta1100)"
        required: true
        type: string

jobs:
  call-release-checksums3:
    uses: ./.github/workflows/release-checksums3.yml
    with:
      tag: ${{ inputs.tag }}
