name: simple-test

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Tag to test"
        required: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Echo tag
        run: echo "Tag is ${{ github.event.inputs.tag }}"
      
      - name: Checkout repo
        uses: actions/checkout@v4
        
      - name: List files
        run: ls -la

